# Generated by Django 2.0.4 on 2018-05-24 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 24, 16, 14, 6, 755812)),
        ),
    ]
