# Generated by Django 2.0.4 on 2018-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_code', models.CharField(max_length=30)),
                ('dept_name', models.CharField(max_length=30)),
            ],
        ),
    ]
