# Generated by Django 2.0.4 on 2018-05-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_fname', models.CharField(max_length=30)),
                ('dept_lname', models.CharField(max_length=30)),
                ('dept_phone', models.CharField(max_length=30)),
                ('dept_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
            ],
        ),
    ]
