# Generated by Django 2.0.7 on 2018-07-13 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='emp_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 12, 23, 7, 291931, tzinfo=utc)),
        ),
    ]
