# Generated by Django 2.0.4 on 2018-05-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept_department',
            new_name='emp_department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dept_fname',
            new_name='emp_fname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dept_lname',
            new_name='emp_lname',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dept_phone',
            new_name='emp_phone',
        ),
    ]
