# Generated by Django 2.0.4 on 2018-05-23 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20180523_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 23, 21, 18, 58, 371907)),
        ),
    ]
