# Generated by Django 2.0.4 on 2018-05-24 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_employee_emp_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 24, 15, 10, 43, 123639)),
        ),
    ]
