# Generated by Django 2.0.4 on 2018-05-24 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20180524_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 24, 15, 11, 57, 428609)),
        ),
    ]
