# Generated by Django 2.0.4 on 2018-05-24 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20180524_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 24, 15, 14, 11, 576788)),
        ),
    ]
